// <auto-generated />
using System;
using Hub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822211756_CriaSchemaPrecos")]
    partial class CriaSchemaPrecos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hub.Domain.Instrumentos.Instrumento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AtivoAte")
                        .HasColumnType("date")
                        .HasColumnName("ativo_ate");

                    b.Property<DateOnly?>("AtivoDesde")
                        .HasColumnType("date")
                        .HasColumnName("ativo_desde");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classe");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Metadados")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadados");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_exibicao");

                    b.Property<bool>("PagaCupom")
                        .HasColumnType("boolean")
                        .HasColumnName("paga_cupom");

                    b.HasKey("Id");

                    b.HasIndex("Classe")
                        .HasDatabaseName("ix_instrumentos_classe");

                    b.ToTable("instrumentos", null, t =>
                        {
                            t.HasCheckConstraint("ck_instrumentos_classe_prefixo", "classe = split_part(id, ':', 1)");
                        });
                });

            modelBuilder.Entity("Hub.Domain.Instrumentos.InstrumentoFonte", b =>
                {
                    b.Property<string>("InstrumentoId")
                        .HasColumnType("text")
                        .HasColumnName("instrumento_id");

                    b.Property<string>("Fonte")
                        .HasColumnType("text")
                        .HasColumnName("fonte");

                    b.Property<string>("CodigoNaFonte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_na_fonte");

                    b.HasKey("InstrumentoId", "Fonte");

                    b.HasIndex("Fonte", "CodigoNaFonte")
                        .IsUnique()
                        .HasDatabaseName("ix_instrumento_fontes_fonte_codigo");

                    b.ToTable("instrumento_fontes", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_em");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("routing_key");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_outbox_pendentes")
                        .HasFilter("publicado_em IS NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Precos.Preco", b =>
                {
                    b.Property<string>("InstrumentoId")
                        .HasColumnType("text")
                        .HasColumnName("instrumento_id");

                    b.Property<DateOnly>("DataRef")
                        .HasColumnType("date")
                        .HasColumnName("data_ref");

                    b.Property<string>("Campo")
                        .HasColumnType("text")
                        .HasColumnName("campo");

                    b.Property<string>("Fonte")
                        .HasColumnType("text")
                        .HasColumnName("fonte");

                    b.Property<int>("Revisao")
                        .HasColumnType("integer")
                        .HasColumnName("revisao");

                    b.Property<DateTimeOffset>("ObservadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observado_em");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("valor");

                    b.HasKey("InstrumentoId", "DataRef", "Campo", "Fonte", "Revisao");

                    b.HasIndex("InstrumentoId", "DataRef")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_precos_lookup");

                    b.ToTable("precos", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Instrumentos.InstrumentoFonte", b =>
                {
                    b.HasOne("Hub.Domain.Instrumentos.Instrumento", null)
                        .WithMany()
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hub.Domain.Precos.Preco", b =>
                {
                    b.HasOne("Hub.Domain.Instrumentos.Instrumento", null)
                        .WithMany()
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
