services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_ADMIN_PW:-admin123}
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
volumes:
  pgdata:
